name = "visitarandomwebsite"
main = "dist/_worker.js/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-29"

[site]
bucket = './dist'

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""
preview_database_id = "DB" 